[project]
name = "llm-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "json5>=0.14.0",
    "streamlit>=1.46.1",
    "streamlit-javascript>=0.1.5",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
